### ISSUE TITLE
Minheldolath? region

### ISSUE THREAD

**Issue by kassoff** [Uvatha/meccg-maps#13]
Up in the top left. Super important place everyone wants to go. /The mousover text reads Minmeldolia, and nothing pops up. I can't quite make out the text on the map, but according to this map it should be Minheldolath.//
![DC Main Map](https://user-images.githubusercontent.com/31231382/99214907-47490200-2786-11eb-84fc-04b49cc96408.jpg)

**Comment by Uvatha** [comment]
Typo in loclist.csv fixed!
