### ISSUE TITLE
Grey Mountain Narrows region missing

### ISSUE THREAD

**Issue by kassoff** [Uvatha/meccg-maps#2]
It's outlined, but doesn't have a name (I assume due to space constraints. There's a shadowlands region symbol, but nothing happens on mouseover of the symbol.

**Comment by Uvatha** [comment]
Grey Mountain Narrows is now correctly tied to the image on the map and resources tied to the region are appearing.  A lot of the issues that you have noted stem from using an incomplete/outdated map so a new map should probably found.
