### ISSUE TITLE
Eryn Lasgalen

### ISSUE THREAD

**Issue by kassoff** [Uvatha/meccg-maps#5]
Eryn Lasgalen is showing up in a lot of regions not relevant to its card text.

**Comment by Uvatha** [comment]
The text "any factions played in Wilderland, Southern Mirkwood" was making the labeler think that the card itself was actually playable.  This is a recurring problem that I'll try to come up with a more general solution for, but for now I just manually excluded Eryn Lasgalen for these regions.
