### ISSUE TITLE
Lakeland

### ISSUE THREAD

**Issue by kassoff** [Uvatha/meccg-maps#8]
Nothing pops up as playable in Lakeland. Since it is a wilderness, shouldn't all the standard cards for any wilderness pop up?

**Comment by kassoff** [comment]
According to this map it is called Lindalf. Could that be the problem?
![DC Main Map](https://user-images.githubusercontent.com/31231382/99214676-aa866480-2785-11eb-8909-e48f7623f153.jpg)

**Comment by Uvatha** [comment]
Same issue as #2 in that we just need a better map.  Might even consider the map you shared here, because it has all the Sunlands regions.  Right now I have all of the cards mapped to regions, but those regions don't appear on the map.
